[manager]
prepend_keymap = [
	{ on = [ "<Esc>" ], run = "close" },
	{ on = ["n"],   run = "create", desc = "Create a file (ends with / for directories)" },
	{ on = [ "e" ], run = "open"},
	{ on = [ "l" ], run = "plugin smart-enter --sync --args='detatch'", desc = "Open in new window." },
	{ on = [ "f" ], run = "plugin jump-to-char", desc = "Jump to char" },
]
