[manager]
prepend_keymap = [
	{ on = [ "e" ], run = "open"},
	{ on = [ "A" ], run = "create --dir"},
	{ on   = "l",		run  = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
	{ on   = "f", run  = "plugin jump-to-char", desc = "Jump to char" }
]
