[manager]
prepend_keymap = [
	{ on = [ "!" ], run = 'shell bash --block --confirm', desc = "Open shell here" },
	{ on = [ "e" ], run = "open"},
	{ on = [ "A" ], run = "create --dir"},
	{ on = "l",		run  = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
	{ on = "f", run  = "plugin jump-to-char", desc = "Jump to char" }
]
[completion]
prepend_keymap = [
	{ on = [ "<C-j>" ], run = [ "arrow 1", "insert" ] },
	{ on = [ "<C-k>" ], run = [ "arrow -1", "insert --append" ] },
]
