"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"
[manager]
ratio          = [ 1, 4, 3 ]
sort_by        = "natural"
sort_sensitive = true
sort_dir_first = true
sort_reverse   = false
linemode       = "size"
show_symlink   = true
show_hidden    = false

[preview]
tab_size        = 2
max_width       = 600
max_height      = 900
cache_dir       = ""
image_filter    = "triangle"
image_quality   = 75
sixel_fraction  = 15
ueberzug_scale  = 1
ueberzug_offset = [ 0, 0, 0, 0 ]

[opener]
edit = [
	{ run = "nvim %*",   block = true, for = "windows" },
]
play = [
	{ run = 'C:\Users\LLI\AppData\Local\Programs\mpv.net\mpvnet.exe %*', orphan = true, for = "windows" }
]
archive = [
	{ run = 'unar "$1"', desc = "Extract here" },
	{ run = 'unar "%1"', desc = "Extract here", for = "windows" },
	{ run = '/Applications/MacZip.app/Contents/MacOS/MacZip "$1"', orphan = true, desc = "MacZip" },
]

[open]
rules = [
	{ name = "*/", use = [ "edit", "open", "reveal" ] },

	{ mime = "text/*",  use = [ "edit", "reveal" ] },
	{ mime = "image/*", use = [ "open", "reveal" ] },
	{ mime = "video/*", use = [ "play", "reveal" ] },
	{ mime = "audio/*", use = [ "play", "reveal" ] },
	{ mime = "inode/x-empty", use = [ "edit", "reveal" ] },

	{ mime = "application/json", use = [ "edit", "reveal" ] },
	{ mime = "*/javascript",     use = [ "edit", "reveal" ] },

	{ mime = "application/zip",             use = [ "extract", "reveal", "archive" ] },
	{ mime = "application/gzip",            use = [ "extract", "reveal", "archive" ] },
	{ mime = "application/x-tar",           use = [ "extract", "reveal", "archive" ] },
	{ mime = "application/x-bzip",          use = [ "extract", "reveal", "archive" ] },
	{ mime = "application/x-bzip2",         use = [ "extract", "reveal", "archive" ] },
	{ mime = "application/x-7z-compressed", use = [ "extract", "reveal", "archive" ] },
	{ mime = "application/x-rar",           use = [ "extract", "reveal", "archive" ] },

	{ name = "*", use = [ "open", "reveal" ] },
]
