# =============================================================================== #
# LazyGit:                                                                        #
# =============================================================================== #
gui:
  scrollHeight: 2
  mainPanelSplitMode: "flexible"
  enlargedSideViewLocation: "left"
  language: "en"
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#8a9a7b"
      - bold
    inactiveBorderColor:
      - "#8ba4b0"
    searchingActiveBorderColor:
      - "#c4b28a"
      - bold
    optionsTextColor:
      - "#8ea4a2"
    selectedLineBgColor:
      - "#201d1d"
    selectedRangeBgColor:
      - "#8a9a7b"
    cherryPickedCommitBgColor:
      - "#c4b28a"
    cherryPickedCommitFgColor:
      - "#8a9a7b"
    unstagedChangesColor:
      - "#c4746e"
    defaultFgColor:
      - default
  commitLength:
    show: true

git:
  paging:
    colorArg: "always"
    pager: "delta --dark --paging=never"
  commit:
    signoff: false
    autoWrapCommitMessage: true
    autoWrapWidth: 72
