live_config_reload = true
working_directory = "C:/Users/LLI"
[shell]
program = "C:/Program Files/Git/bin/bash.exe"
# program = "C:/msys64/msys2_shell.cmd"
# args = ["-defterm -here -no-start -ucrt64 -full-path -shell bash"]
[window]
opacity = 0.98
padding.x = 10
padding.y = 10
decorations = "None"
decorations_theme_variant = "Dark"
[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 10.0
offset = { x = 0, y = 0}
glyph_offset = { x = 0, y = 0}
[scrolling]
history = 50000
multiplier = 3
[env]
TERM = "xterm-256color"
