working_directory = "C:/Users/LLI"
[shell]
program = "pwsh -nologo"
# program = "C:/Program Files/Git/bin/bash.exe"
# program = "C:/msys64/msys2_shell.cmd"
# args = ["-defterm -here -no-start -ucrt64 -full-path -shell bash"]
[window]
opacity = 1.0
padding = {x= 10, y=20}
dynamic_padding = true
decorations = "None"
[font]
normal = { family = "JetBrainsMono NF", style = "Bold" }
bold = { family = "JetBrainsMono NF", style = "Bold" }
italic = { family = "JetBrainsMono NF", style = "Italic" }
bold_italic = { family = "JetBrainsMono NF", style = "Bold Italic" }
size = 11.0
[scrolling]
history = 50000
multiplier = 3
# ===================================================#
# colorsscheme:                                      #
# ===================================================#
[colors.primary]
background = '#1d2021'
foreground = '#d4be98'

# Normal colors
[colors.normal]
black   = '#32302f'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'

# Bright colors (same as normal colors)
[colors.bright]
black   = '#32302f'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'
