# ===================================================#
# General:                                           #
# ===================================================#
working_directory = "C:/Users/LLI"
live_config_reload = true
[shell]
program = "pwsh -nologo"
# program = "C:/Program Files/Git/bin/bash.exe"
# program = "C:/msys64/msys2_shell.cmd"
# args = ["-defterm -here -no-start -ucrt64 -full-path -shell bash"]
[window]
opacity = 1.0
padding = {x= 10, y=20}
dynamic_padding = true
decorations = "None"
[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
offset.x = 0
offset.y = 2
size = 11
[scrolling]
history = 50000
multiplier = 3
[cursor]
style = { shape = "Beam", blinking = "On" }
vi_mode_style = {shape = "Block", blinking = "Off"}
[terminal]
osc52 = "CopyPaste"
# ===================================================#
# colorsscheme:                                      #
# ===================================================#
[colors.primary]
background = '#1d2021'
foreground = '#d4be98'
[colors.normal]
black   = '#32302f'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'
[colors.bright]
black   = '#32302f'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'
# ===================================================#
# keybidings:                                        #
# ===================================================#
[keyboard]
bindings = [
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "Paste", action = "Paste" },
  { key = "Copy", action = "Copy" },
  { key = "Insert", mods = "Shift", action = "PasteSelection" },
  { key = "F", mods = "Control|Shift", action = "SearchForward", mode = "~Search" },
  { key = "B", mods = "Control|Shift", action = "SearchBackward", mode = "~Search" },
  { key = "Key0", mods = "Control", action = "ResetFontSize" },
  { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
  { key = "L", mods = "Control", action = "ClearLogNotice" },
  { key = "L", mods = "Control", chars = "\f" },
  { key = "PageUp", mods = "Shift", action = "ScrollPageUp", mode = "~Alt" },
  { key = "PageDown", mods = "Shift", action = "ScrollPageDown", mode = "~Alt" },
  { key = "Up", mods = "Shift", action = "ScrollLineUp", mode = "~Alt" },
  { key = "Down", mods = "Shift", action = "ScrollLineDown", mode = "~Alt" },
  { key = "Home", mods = "Shift", action = "ScrollToTop", mode = "~Alt" },
  { key = "End", mods = "Shift", action = "ScrollToBottom", mode = "~Alt" },
  { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
]
